# Generated by Django 5.0.2 on 2024-03-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
